sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7QW8VX4FE4ch2oiH7F
    access-key-secret: fU1ARJ9hoFBx5pGnggULSXlF3Si26m
    bucket-name: project-sky-zggyii
